###list users
GET http://localhost:3001/api/users

###user by id
GET http://localhost:3001/api/users/2

###add user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstname": "teste2",
  "surname": "teste2",
  "email": "user2@mail.com",
  "password": "123@123"
}  

###update user
PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "firstname": "mudei carai",
  "surname": "user surname",
  "email": "user@mail.com",
  "password": "123@123"
}  

###delete user
DELETE http://localhost:3001/api/users/2